name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Restore npm cache
      uses: actions/cache@v2.1.6
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - run: npm ci
    - run: npm run test
    - run: npm run build
    - name: Copy sample sketch.json
      run: cp docs/sample_sketch.json sketch.json
    - name: testrun
      uses: ./
    - name: Update dist
      uses: test-room-7/action-update-file@v1.6.0
      with:
        file-path: dist/*.js
        commit-msg: Update dist
        github-token: ${{ secrets.GITHUB_TOKEN }}
